
USE sucos_vendas
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES

SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO 
IN ('Tijuca', 'Copacabana', 'Santo Amaro', 'Jardins')

SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO 
IN (SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES)

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAXIMO FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM

SELECT X.EMBALAGEM, X.PRECO_MAXIMO FROM 
(SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAXIMO FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM) X WHERE X.PRECO_MAXIMO >= 10

-- Retorna o cpf e ano do mesmo que seja maior que 2000, contando aqueles em que a data de venda foi do ano de 2016 
  SELECT CPF, COUNT(*) as CONTADOR FROM notas_fiscais
  WHERE YEAR(DATA_VENDA) = 2016
  GROUP BY CPF
  HAVING COUNT(*) > 2000

  SELECT X.CPF, X.CONTADOR FROM 
  (SELECT CPF, COUNT(*) AS CONTADOR FROM notas_fiscais
  WHERE YEAR(DATA_VENDA) = 2016
  GROUP BY CPF) X WHERE X.CONTADOR > 2000