
SELECT * FROM TABELA_DE_VENDEDORES

SELECT * FROM TABELA_DE_CLIENTES

--Traz os dados referentes aos vendedores e clientes com bairros iguais
SELECT * FROM TABELA_DE_VENDEDORES INNER JOIN TABELA_DE_CLIENTES
ON TABELA_DE_VENDEDORES.BAIRRO = TABELA_DE_CLIENTES.BAIRRO

--De férias é só referente à tabela de vendedores
SELECT TABELA_DE_VENDEDORES.BAIRRO,
TABELA_DE_VENDEDORES.NOME, DE_FERIAS,
TABELA_DE_CLIENTES.BAIRRO,
TABELA_DE_CLIENTES.NOME FROM TABELA_DE_VENDEDORES INNER JOIN TABELA_DE_CLIENTES
ON TABELA_DE_VENDEDORES.BAIRRO = TABELA_DE_CLIENTES.BAIRRO

--Tem escritório em Copacabana mas não tem cliente lá
SELECT TABELA_DE_VENDEDORES.BAIRRO,
TABELA_DE_VENDEDORES.NOME, DE_FERIAS,
TABELA_DE_CLIENTES.BAIRRO,
TABELA_DE_CLIENTES.NOME FROM TABELA_DE_VENDEDORES LEFT JOIN TABELA_DE_CLIENTES
ON TABELA_DE_VENDEDORES.BAIRRO = TABELA_DE_CLIENTES.BAIRRO

--Tem clientes, mas não tem escritórios em alguns casos
SELECT TABELA_DE_VENDEDORES.BAIRRO,
TABELA_DE_VENDEDORES.NOME, DE_FERIAS,
TABELA_DE_CLIENTES.BAIRRO,
TABELA_DE_CLIENTES.NOME FROM TABELA_DE_VENDEDORES RIGHT JOIN TABELA_DE_CLIENTES
ON TABELA_DE_VENDEDORES.BAIRRO = TABELA_DE_CLIENTES.BAIRRO

--Junta e mostra os casos que tem correspodencia ou nao
SELECT TABELA_DE_VENDEDORES.BAIRRO,
TABELA_DE_VENDEDORES.NOME, DE_FERIAS,
TABELA_DE_CLIENTES.BAIRRO,
TABELA_DE_CLIENTES.NOME FROM TABELA_DE_VENDEDORES FULL JOIN TABELA_DE_CLIENTES
ON TABELA_DE_VENDEDORES.BAIRRO = TABELA_DE_CLIENTES.BAIRRO

--Cross join faz analise combinatoria