
SELECT COUNT(*) FROM TABELA_DE_CLIENTES --15 retornos

SELECT CPF, COUNT(*) FROM NOTAS_FISCAIS GROUP BY CPF --14 retornos

--traz os valores correspondentes

SELECT DISTINCT A.CPF, A.NOME, B.CPF FROM TABELA_DE_CLIENTES A
INNER JOIN NOTAS_FISCAIS B ON A.CPF = B.CPF 

--traz todos da esquerda (notar o nulo no da direita)

SELECT DISTINCT A.CPF, A.NOME, B.CPF FROM TABELA_DE_CLIENTES A
LEFT JOIN NOTAS_FISCAIS B ON A.CPF = B.CPF 

--traz apenas o b.cpf que é nulo
SELECT DISTINCT A.CPF, A.NOME, B.CPF FROM TABELA_DE_CLIENTES A
LEFT JOIN NOTAS_FISCAIS B ON A.CPF = B.CPF 
WHERE B.CPF IS NULL

--trazer todos cpfs e nomes referentes às compras de 2015
SELECT DISTINCT A.CPF, A.NOME, B.CPF FROM TABELA_DE_CLIENTES A
LEFT JOIN NOTAS_FISCAIS B ON A.CPF = B.CPF 
WHERE YEAR(B.DATA_VENDA) = 2015