SELECT CURRENT_TIMESTAMP as resultado;

SELECT CONCAT('O dia de hoje é : ', CURRENT_TIMESTAMP) AS RESULTADO;

SELECT CONCAT('O dia de hoje é : ', FORMAT(CURRENT_TIMESTAMP, 'dd-MM-yyyy HH:mm:ss')) AS RESULTADO;