SELECT * FROM ITENS_NOTAS_FISCAIS

SELECT * FROM NOTAS_FISCAIS


--Junta as duas tabelas
SELECT * FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO

--Traz os dados mas repete CPF e datas de venda
SELECT NF.CPF, NF.DATA_VENDA, INF.QUANTIDADE FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO

--Arrumando mês e ano
SELECT NF.CPF, FORMAT(NF.DATA_VENDA, 'MM-yyyy') as MES_ANO, INF.QUANTIDADE FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO

--Consulta com vendas de clientes por mês
SELECT NF.CPF, TC.NOME, FORMAT(NF.DATA_VENDA, 'yyyy-MM') as MES_ANO, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDA, 
MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC
ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, FORMAT(NF.DATA_VENDA, 'yyyy-MM')

--Limite de compra por cliente
SELECT * FROM TABELA_DE_CLIENTES;

SELECT NF.CPF, TC.NOME, FORMAT(NF.DATA_VENDA, 'yyyy-MM') as MES_ANO, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDA, 
MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC
ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, FORMAT(NF.DATA_VENDA, 'yyyy-MM')

--Usando uma subquery
SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDAS, X.QUANTIDADE_LIMITE,
CASE WHEN (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0 THEN 'INVÁLIDA'
ELSE 'VÁLIDA' END AS STATUS_VENDA
FROM (
SELECT NF.CPF, TC.NOME, FORMAT(NF.DATA_VENDA, 'yyyy-MM') AS MES_ANO
, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS 
, MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC 
ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, FORMAT(NF.DATA_VENDA, 'yyyy-MM')) X;